### ISSUE TITLE
babel-plugin-module-resolver TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by joelachance** [codebushi/nextjs-starter-forty#1]
First, we need to require Node >8. This project does not run on versions below 8. Second, after cloning, this doesn't run out of the box. We have some issues with Babel and our Sass modules here.

**Comment by eddiecervello** [comment]
Simple fix out of the box is to uninstall and reinstall the babel-plugin-module-resolver package.

**Comment by purplemulemedia** [comment]
I created a pull request to update the babel-plugin-module-resolver to correct this issue

**Comment by ChangoMan** [comment]
This has been fixed
